version: "3.3"

volumes:
  mongodata:
    name: tomoscan_mongodbdata

services:
  gateway:
    image: ${DOCKER_TAG_BASE}epics-gateway-run:${DOCKER_TAG_VERSION}
    ports:
      - "50640:50640"
      - "5064:50640/udp"  # MOFIFY the port 5064 to something else when running multiple instances on the same subnet.
    env_file:
      - epics.env
  areadetector:
    image: ad-ioc
    stdin_open: true
    stop_signal: "SIGKILL"
    volumes:
      - type: bind
        source: ./data
        target: /out
    env_file:
      - epics.env
      
  mongo-db:
    image: mongo
    #network_mode: "host"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db


